# Render Blueprint — Apotek POS Demo
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: apotek-pos-demo
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    branch: main
    envVars:
      - key: APP_NAME
        value: "Apotek POS Demo"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://apotek-pos-demo.onrender.com"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        value: apotek_pos_demo
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: stderr
      - key: DEMO_MODE
        value: "true"
      - key: DEMO_RESET_HOURS
        value: "2"
